export const ADD_FIELD_START='ADD_FIELD_START';
export const ADD_FIELD_END='ADD_FIELD_END';
export const ADD_FIELD_FAIL='ADD_FIELD_FAIL';
export const ADD_FIELD_SUCCESS='ADD_FIELD_SUCCESS';
export const ADD_TYPE_FAIL='ADD_TYPE_FAIL';
export const ADD_EDIT_FAIL='ADD_EDIT_FAIL';
export const ADD_CLASS_FAIL='ADD_CLASS_FAIL';
export const ADD_OR_FAIL='ADD_OR_FAIL';
export const ADD_TH_FAIL='ADD_TH_FAIL';
export const ADD_TOME_FAIL='ADD_TOME_FAIL';
export const ADD_FORMAT_FAIL='ADD_FORMAT_FAIL';
export const FETCH_TOME_SUCCESS='ADD_TOME_SUCCESS';
export const ADD_AUT_FAIL='ADD_AUT_FAIL';

export const AUTH_START='AUTH_START';
export const AUTH_END='AUTH_END';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_SUCCESS='AUTH_SUCCESS';

export const LOGOUT_START='LOGOUT_START';
export const LOGOUT_END='LOGOUT_END';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';


export const FETCH_STATS_START='FETCH_STATS_START';
export const FETCH_STATS_END='FETCH_STATS_END';
export const FETCH_STATS_FAIL='FETCH_STATS_FAIL';
export const FETCH_STATS_SUCCESS='FETCH_STATS_SUCCESS';

export const FETCH_FIELDS_START='FETCH_FIELDS_START';
export const FETCH_FIELDS_END='FETCH_FIELDS_END';
export const FETCH_FIELDS_FAIL='FETCH_FIELDS_FAIL';
export const FETCH_FIELDS_SUCCESS='FETCH_FIELDS_SUCCESS';

export const FETCH_EXPUNITE_START='FETCH_EXPUNITE_START';
export const FETCH_EXPUNIT_END='FETCH_EXPUNITE_END';
export const FETCH_EXPUNIT_FAIL='FETCH_EXPUNITE_FAIL';
export const FETCH_EXPUNIT_SUCCESS='FETCH_EXPUNITE_SUCCESS';

export const ADD_EXPUNITE_START='ADD_EXPUNITE_START';
export const ADD_EXPUNIT_END='ADD_EXPUNITE_END';
export const ADD_EXPUNIT_FAIL='ADD_EXPUNITE_FAIL';
export const ADD_EXPUNIT_SUCCESS='ADD_EXPUNITE_SUCCESS';


export const FETCH_OUVID_START='FETCH_OUVID_START';
export const FETCH_OUVID_END='FETCH_OUVID_END';
export const FETCH_OUVID_FAIL='FETCH_OUVID_FAIL';
export const FETCH_OUVID_SUCCESS='FETCH_OUVID_SUCCESS';


export const ADD_OUV_START='ADD_OUV_START';
export const ADD_OUV_END='ADD_OUV_END';
export const ADD_OUV_FAIL='ADD_OUV_FAIL';
export const ADD_OUV_SUCCESS='ADD_OUV_SUCCESS';


export const FETCH_OUV_START='FETCH_OUV_START';
export const FETCH_OUV_END='FETCH_OUV_END';
export const FETCH_OUV_FAIL='FETCH_OUV_FAIL';
export const FETCH_OUV_SUCCESS='FETCH_OUV_SUCCESS';



export const FETCH_THUN_START='FETCH_THUN_START';
export const FETCH_THUN_END='FETCH_THUN_END';
export const FETCH_THUN_FAIL='FETCH_THUN_FAIL';
export const FETCH_THUN_SUCCESS='FETCH_THUN_SUCCESS';

export const FETCH_EVENTS_START='FETCH_EVENTS_START';
export const FETCH_EVENTS_END='FETCH_EVENTS_END';
export const FETCH_EVENTS_FAIL='FETCH_EVENTS_FAIL';
export const FETCH_EVENTS_SUCCESS='FETCH_EVENTS_SUCCESS';

export const ADD_EVENTS_START='ADD_EVENTS_START';
export const ADD_EVENTS_END='ADD_EVENTS_END';
export const ADD_EVENTS_FAIL='ADD_EVENTS_FAIL';
export const ADD_EVENTS_SUCCESS='ADD_EVENTS_SUCCESS';


export const FETCH_TOPTEN_START='FETCH_TOPTEN_START';
export const FETCH_TOPTEN_END='FETCH_TOPTEN_END';
export const FETCH_TOPTEN_FAIL='FETCH_TOPTEN_FAIL';
export const FETCH_TOPTEN_SUCCESS='FETCH_TOPTEN_SUCCESS';

export const DEL_EVENTS_START='DEL_EVENTS_START';
export const DEL_EVENTS_END='DEL_EVENTS_END';
export const DEL_EVENTS_FAIL='DEL_EVENTS_FAIL';
export const DEL_EVENTS_SUCCESS='DEL_EVENTS_SUCCESS';

export const FETCH_TOPFIVE_START='FETCH_TOPFIVE_START';
export const FETCH_TOPFIVE_END='FETCH_TOPFIVE_END';
export const FETCH_TOPFIVE_FAIL='FETCH_TOPFIVE_FAIL';
export const FETCH_TOPFIVE_SUCCESS='FETCH_TOPFIVE_SUCCESS';

export const FETCH_TOPTWO_START='FETCH_TOPTWO_START';
export const FETCH_TOPTWO_END='FETCH_TOPTWO_END';
export const FETCH_TOPTWO_FAIL='FETCH_TOPTWO_FAIL';
export const FETCH_TOPTWO_SUCCESS='FETCH_TOPTWO_SUCCESS';


export const FETCH_FIELDSDOC_START='FETCH_FIELDSDOC_START';
export const FETCH_FIELDSDOC_END='FETCH_FIELDSDOC_END';
export const FETCH_FIELDSDOC_FAIL='FETCH_FIELDSDOC_FAIL';
export const FETCH_FIELDSDOC_SUCCESS='FETCH_FIELDSDOC_SUCCESS';

export const FETCH_LECTEURS_START='FETCH_LECTEURS_START';
export const FETCH_LECTEURS_END='FETCH_LECTEURS_END';
export const FETCH_LECTEURS_FAIL='FETCH_LECTEURS_FAIL';
export const FETCH_LECTEURS_SUCCESS='FETCH_LECTEURS_SUCCESS';